### ISSUE TITLE
An error occured while starting 11.2.0.2 image

### ISSUE THREAD

**Issue by little-fish** [oracle/docker-images#756]
Hello.
I was able to create image for 11.2.0.2.
`Oracle Database Docker Image for 'xe' version 11.2.0.2 is ready to be extended:
    --> oracle/database:11.2.0.2-xe
`

But once I execute docker run:
`docker run --name oracle-11g-xe-dev --shm-size=2g -d -p 1521:1521 -p 8082:8080 -e ORACLE_PWD=SomePassword12 oracle/database:11.2.0.2-xe`
it outputs following:
```
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
```

Here is the log file.
[alert_XE.log](https://github.com/oracle/docker-images/files/1724141/alert_XE.log)
Those errors listed in the log say nothing to me.

I have tried to build the image several times but had no luck with executing it.
Thanks for any help.

**Comment by mbarre** [comment]
Hi,
I have the same problem with the same image.

**Comment by gvenzl** [comment]
Hi @little-fish, can you please give me the entire `docker log` output, please. Looks like something went wrong further above.

**Comment by little-fish** [comment]
Hi @gvenzl.
Here is the build log:
`$ ./buildDockerImage.sh -v 11.2.0.2 -x > build.log`
[build.log](https://github.com/oracle/docker-images/files/1726568/build.log)

Here is the run log:
`docker run --name oracle-11g-xe-dev --shm-size=2g -d -i -t -p 1521:1521 -p 8082:8080 -e ORACLE_PWD=adminAdmin12 oracle/database:11.2.0.2-xe`
`docker logs oracle-11g-xe-dev > run.log`
[run.log](https://github.com/oracle/docker-images/files/1726569/run.log)

Hope they will help you.
Thanks.

**Comment by gvenzl** [comment]
Hi @little-fish, I believe that error is just a red herring. According to the log and the output before and after the error message, the database is up and running. Seems like that the error reporting is off because of this:

```
ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
```
Which leads to the wrong error reporting:
```
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
```
However, I can't reproduce this on my environment. Have you built this on the latest Dockerfiles?

**Comment by sakateka** [comment]
I have the same problem.

**Comment by Magic798** [comment]
Me too, also 11.2.0.2 XE. Connecting to the database works, but Portainer shows the container als unhealthy.

**Comment by schaary** [comment]
I have the same problem.

To set `ORACLE_BASE` manually doesn't fix anything:

```bash
- 11.2.0.2 · master →  docker run --name idm-xe --shm-size=2g -p 1521:1521 -p 5500:5500  -e ORACLE_CHARACTERSET=WE8ISO8859P1  -e ORACLE_BASE=/u01/app/oracle oracle/database:11.2.0.2-xe
ORACLE PASSWORD FOR SYS AND SYSTEM: e4444e35f193b9f4

Oracle Database 11g Express Edition Configuration
-------------------------------------------------
This will configure on-boot properties of Oracle Database 11g Express
Edition.  The following questions will determine whether the database should
be starting upon system boot, the ports it will use, and the passwords that
will be used for database accounts.  Press <Enter> to accept the defaults.
Ctrl-C will abort.

Specify the HTTP port that will be used for Oracle Application Express [8080]:
Specify a port that will be used for the database listener [1521]:
Specify a password to be used for database accounts.  Note that the same
password will be used for SYS and SYSTEM.  Oracle recommends the use of
different passwords for each database account.  This can be done after
initial configuration:
Confirm the password:

Do you want Oracle Database 11g Express Edition to be started on boot (y/n) [y]:
Starting Oracle Net Listener...Done
Configuring database...Done
Starting Oracle Database 11g Express Edition instance...Done
Installation completed successfully.

SQL*Plus: Release 11.2.0.2.0 Production on Fri Feb 16 16:23:57 2018

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL>
PL/SQL procedure successfully completed.

SQL> SQL>
Database altered.

SQL>
Database altered.

SQL>
Database altered.

SQL>
System altered.

SQL>
System altered.

SQL>
System altered.

SQL>
Database altered.

SQL>
Database altered.

SQL> SQL>
System altered.

SQL> Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
  Current log# 5 seq# 4 mem# 0: /u01/app/oracle/oradata/XE/redo05.log
      ALTER DATABASE DROP LOGFILE GROUP 1
Deleted Oracle managed file /u01/app/oracle/fast_recovery_area/XE/onlinelog/o1_mf_1_f8g1cojf_.log
Completed:       ALTER DATABASE DROP LOGFILE GROUP 1
      ALTER DATABASE DROP LOGFILE GROUP 2
Deleted Oracle managed file /u01/app/oracle/fast_recovery_area/XE/onlinelog/o1_mf_2_f8g1cows_.log
Completed:       ALTER DATABASE DROP LOGFILE GROUP 2
Cleared LOG_ARCHIVE_DEST_1 parameter default value
Using LOG_ARCHIVE_DEST_1 parameter default value as /u01/app/oracle/product/11.2.0/xe/dbs/arch
ALTER SYSTEM SET db_recovery_file_dest='' SCOPE=BOTH;
```

**Comment by Magic798** [comment]
@gvenzl: is this a problem with the Dockerfile, since multiple people seem to be having the same issue with it? Is there any workaround? Setting ORACLE_BASE manually like Schaary tried doesn't seem to fix the problem.

The database is usable it seems, but Portainer marks the containers as unhealthy because of the error.

**Comment by soedar** [comment]
I've encountered the similiar issues, and I've narrowed it down to some of the env variables set in `checkDBStatus.sh`. This patch should "fix" the health check failing.

```diff
- ORACLE_SID="`grep $ORACLE_HOME /etc/oratab | cut -d: -f1`"
- ORAENV_ASK=NO
- source oraenv
```

I've added a `env` command immediately after these lines to see the env variables that are set for both when the patch is applied and when it isn't:

**With patch**
```
CONFIG_RSP=xe.rsp
HOSTNAME=eebd132b74cc
TERM=xterm
INSTALL_DIR=/install
ORACLE_SID=XE
ORACLE_BASE=/u01/app/oracle
INSTALL_FILE_1=oracle-xe-11.2.0-1.0.x86_64.rpm.zip
CHECK_DB_FILE=checkDBStatus.sh
PATH=/u01/app/oracle/product/11.2.0/xe/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
PWD=/u01/app/oracle
PWD_FILE=setPassword.sh
RUN_FILE=runOracle.sh
HOME=/root
SHLVL=2
ORACLE_PWD=oracle
ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
```

**Without Patch (`oraenv` appears to prompt for `ORACLE_HOME`, so I simply hit enter to go through)**
```
grep: /etc/oratab: No such file or directory
ORACLE_HOME = [/u01/app/oracle] ? 
ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
CONFIG_RSP=xe.rsp
HOSTNAME=eb58a928a96f
TERM=xterm
INSTALL_DIR=/install
LD_LIBRARY_PATH=/u01/app/oracle/lib
ORACLE_SID=
INSTALL_FILE_1=oracle-xe-11.2.0-1.0.x86_64.rpm.zip
CHECK_DB_FILE=checkDBStatus.sh
PATH=/u01/app/oracle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/u01/app/oracle
PWD_FILE=setPassword.sh
RUN_FILE=runOracle.sh
HOME=/root
SHLVL=2
ORACLE_PWD=oracle
ORACLE_HOME=/u01/app/oracle
_=/usr/bin/env
./checkDBStatus.sh: line 27: sqlplus: command not found
```

@gvenzl could you please advice if it is safe to apply this patch?

**Comment by gvenzl** [comment]
Ok, the good news is that I can reproduce this now and I think I've also already found a fix for this. The issue is that the status check tries to connect via `sqlplus / as sysdba` as the `root` user which isn't allowed. Therefore the status check doesn't go through and the script assume that something went wrong.

The fix I believe is to execute `sqlplus` as the `oracle` user, testing this right now.

Note, setting the `ORACLE_BASE` environment variable makes no difference either in that case. It's just pointing to the same issue, that this is run as the `root` user, but has nothing to do with `sqlplus / as sysdba` not being able to connect.

**Comment by gvenzl** [comment]
Fixed! :)

**Comment by tetardv** [comment]
Hello,
I am facing same issue with Oracle Database 12.2.0.1 Standard Edition. 
The database is up, i can connect and manually execute SQL but, I believe, It is blocking my setup scripts to be executed. 
I have change checkDBStatus.sh by executing sqlplus as my user but I still have the issue.

my error is the same as you already talk = 

ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.

which leads to =
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!

Could I have a hint please ?
Thanks for any help !

**Comment by gvenzl** [comment]
Hi @tetardv, please open a new issue with the log output and all the details in order to help you on this.
Thanks!

**Comment by erhantuncel** [comment]
Hi @gvenzl I have same problem with Oracle 11.2.0.2 xe edition. I have used latest fixed docker-image files. I have built docker image successfully. But when I execute docker run command I got error.

```
grep: /etc/oratab: No such file or directory
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
########### E R R O R ###############
#####################################
The following output is now a tail of the alert.log:
Database Characterset is AL32UTF8
Opening with Resource Manager plan: INTERNAL_PLAN_XE 
Starting background process VKRM
Sat Apr 28 21:15:37 2018
VKRM started with pid=24, OS id=232 
replication_dependency_tracking turned off (no async multimaster replication found)
Starting background process QMNC
Sat Apr 28 21:15:37 2018
QMNC started with pid=23, OS id=240 
Completed: ALTER DATABASE OPEN
Starting background process CJQ0
Sat Apr 28 21:15:38 2018
CJQ0 started with pid=27, OS id=263 
Setting Resource Manager plan SCHEDULER[0x30FC]:DEFAULT_MAINTENANCE_PLAN via scheduler window
```

**Comment by gvenzl** [comment]
Hi @erhantuncel, can you please open a new issue and post the entire `docker build` and `docker run` output. Seems like that `/etc/oratab` was never created which is done during the image build.

**Comment by gutschet** [comment]
Issue still occurs on 19.3.0
The comment from @soedar helped me to figure it out.
I executed `env` directly before the `checkDBStatus.sh`script and inside the script directly before and after `oraenv`.

Before checkDBStatus.sh:
```
...
ORACLE_HOME=/opt/oracle/product/19c/dbhome_1
PATH=/opt/oracle/product/19c/dbhome_1/bin:/opt/oracle/product/19c/dbhome_1/OPatch/:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
...
```
Inside checkDBStatus.sh, before oraenv:
```
...
ORACLE_HOME=/opt/oracle/product/19c/dbhome_1
PATH=/opt/oracle/product/19c/dbhome_1/bin:/opt/oracle/product/19c/dbhome_1/OPatch/:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
...
```
Inside checkDBStatus.sh, afteroraenv:
```
...
ORACLE_HOME=/home/oracle/
PATH=/home/oracle/bin:/opt/oracle/product/19c/dbhome_1/OPatch/:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
...
```

**Comment by cjbj** [comment]
@gutschet is `ORACLE_SID` being set correctly?  If not, try some other syntaxes, e.g. use `export ORACLE_SID=...` and/or
```
ORACLE_SID="`grep $ORACLE_HOME /etc/oratab | sed 's/:.*//'`"
```

**Comment by gutschet** [comment]
@cjbj I am setting ORACLE_SID when running the container via environment. It gets overwritten in `checkDBStatus.sh` with the following command:

```
ORACLE_SID="`grep $ORACLE_HOME /etc/oratab | cut -d: -f1`"
```

Before execution of `oraenv` in `checkDBStatus.sh`, ORACLE_SID is set correctly (TESTDB), after `oraenv`it is empty.
